# Generated by Django 3.2.9 on 2021-11-07 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='ticket',
            new_name='ticker',
        ),
    ]
